
AllCops:
  NewCops: enable
  SuggestExtensions: false
Metrics/AbcSize:
  Enabled: true
  Max: 25
Metrics/ClassLength:
  Max: 130
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
